name: Obsolete Term 
description: Request that a term be obsoleted.
title: "[Obsolete]: "
labels: ["obsolete"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this obsolete term report!
  - type: input
    id: id-to-obsolete
    attributes:
      label: What term do you want to request obsoleting?
      description: Add the MONDO ID formatted as MONDO:1234567.
      # placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: label-to-obsolete
    attributes:
      label: What is the label of the term you want to request obsoleting?
      description: Add the term name.
    validations:
      required: true
  - type: dropdown
    id: obsoletion-reason
    attributes:
      label: Obsoletion reason
      description: What version of our software are you running?
      options:
        - option 1
        - option 2
        - option 3
      default: 0
    validations:
      required: false
  - type: textarea
    id: obsoletion-reason-description
    attributes:
      label: Explain why this term should be obsoleted
      description: Why should this term be obsoleted?
    validations:
      required: true
