name: Obsolete Term 
description: Request that a term be obsoleted.
title: "[Obsolete]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this obsolete term report!
  - type: input
    id: id-to-obsolete
    attributes:
      label: What term do you want to request obsoleting?
      description: Add the MONDO ID formatted as MONDO:1234567.
      # placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: label-to-obsolete
    attributes:
      label: What is the label of the term you want to request obsoleting?
      description: Add the term name.
      # placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: obsoletion-reason
    attributes:
      label: Reason for obsoletion
      description: Why should this term be obsoleted?
    validations:
      required: true
