name: Obsolete Issue Check

on:
  issues:
    types: [labeled]

jobs:
  check_issue_body:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: List directory contents
        run: ls -lR
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          if echo "${{ github.event.issue.title }}" | grep -iq "obsolete"; then
            echo "Issue Title contains the word 'obsolete'."
            export ISSUE_BODY="${{ github.event.issue.body }}"
            python submit_to_google_sheet.py
          else
            echo "Issue Title does not contain the word 'obsolete'."
          fi
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      # - name: Check if issue body contains "obsolete"
      #   uses: actions/github-script@v5
      #   with:
      #     github-token: ${{ secrets.GH_TOKEN }}
      #     script: |
      #       const issue = await github.issues.get({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number
      #       });

      #       const issueBody = issue.data.body.toLowerCase(); // Convert to lowercase for case-insensitive check
      #       const containsObsolete = issueBody.includes('obsolete');

      #       console.log(`Issue body contains "obsolete": ${containsObsolete}`);

      #       if (containsObsolete) {
      #         console.log('Obsolete text found in issue body.');

      #         // Here you can add actions to perform when the issue contains "obsolete"
      #         // For example, you can add a comment to the issue.
      #         await github.issues.createComment({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           issue_number: context.issue.number,
      #           body: 'Please review the issue. It contains the term "obsolete".'
      #         });
      #       }
