name: Obsolete Issue Check

on:
  issues:
    types: [opened]

jobs:
  check_issue_body:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue body contains "obsolete"
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const issueBody = issue.data.body.toLowerCase(); // Convert to lowercase for case-insensitive check
            const containsObsolete = issueBody.includes('obsolete');

            console.log(`Issue body contains "obsolete": ${containsObsolete}`);

            if (containsObsolete) {
              console.log('Obsolete text found in issue body.');

              // Here you can add actions to perform when the issue contains "obsolete"
              // For example, you can add a comment to the issue.
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: 'Please review the issue. It contains the term "obsolete".'
              });
            }
