name: Obsolete Issue Check

on:
  issues:
    types: [labeled]

jobs:
  check_issue_body:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - name: List directory contents
      #   run: ls -lR
      - name: Check if label exists
        id: check_label
        if: |
          contains(github.event.issue.labels.*.name, 'on the list')
        run: |
          echo "Issue label contains 'on the list'"
          echo "::set-output name=label_found::true"

      - name: Process based on label existence
        if: steps.check_label.outputs.label_found == 'true'
        run: |
          # Perform actions if the label is found
          echo "Performing actions because the label is found"
      
      # - name: Check if label exists
      #   if: |
      #     contains(github.event.issue.labels.*.name, 'on the list')
      #   run: |
      #     echo "Issue label contains 'on the list'"
      # - name: Install dependencies
      #   run: |
      #     cd $GITHUB_WORKSPACE
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: View issue information
      #   run: |
      #     echo "Issue title: ${{ github.event.issue.title }}"
      #     echo "Issue body: ${{ github.event.issue.body }}"
      #     for label in "${{ github.event.issue.labels }}"; do
      #       echo "Label name: $label"
      #     done
      #     if echo "${{ github.event.issue.title }}" | grep -q "[Obsolete]:"; then
      #       echo "Issue Title contains the word '[Obsolete]: and is from an Obsolete Issue template'."
      #       export ISSUE_BODY="${{ github.event.issue.body }}"
      #       python submit_to_google_sheet.py
      #     else
      #       echo "Issue Title does not contain the word '[Obsolete]:'."
      #     fi
      #   env:
      #     GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

